const types = {
  'GET_CONTACT_LIST': 'GET_CONTACT_LIST',
  'SET_CONTACT_LIST': 'SET_CONTACT_LIST',
  'GET_CONTACT_DETAIL': 'GET_CONTACT_DETAIL',
  'SET_CONTACT_DETAIL': 'SET_CONTACT_DETAIL'
}

export default types
